### ISSUE TITLE
Image Loading in Markdown Enabled Fields

### ISSUE THREAD

**Issue by jlyon1** [wtg/elections#94]
Candidates can load in an arbitrary image using markdown in the about field/platform field. Depending on the size of the image, this messes with the layout of the page, and the image can go far off the page.

**Comment by kochman** [comment]
We support most HTML by design. Security-wise, script and style tags get stripped client-side by Angular's sanitize service. Additionally, the Content Security Policy prevents linking to most resources that aren't from the same origin. If any candidate intentionally misuses the site, the Elections Commission has the power to issue a sanction.

We could probably do a better job of handling this stuff. For example, we could set an image max width inside of the candidate profile just in case a candidate includes an image and doesn't set its width. I'd welcome a PR.
